### ISSUE TITLE
You can't open up the linked documents in separate tabs

### ISSUE THREAD

**Issue by jonathanwestin** [CDH-DevTeam/context-frontend#5]
When command-click (Mac) on a linked full text document to open it in a separate tab for later reading, the page gets an error message with the text: "Not Found The requested URL /document/148039 was not found on this server". 

Related bug: this also prevents sharing of individual document-pages since you can't copy the url, for instance "https://kontext.dh.gu.se/document/148039", and copy it into another browser window.

**Comment by arildm** [comment]
Fixed by modifying the copy command in the deploy script, so that the `.htaccess` file is included.
